name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
env:
  isRelease: ${{ contains(github.ref, 'tags') }}

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Check out source code
      uses: actions/checkout@v2

    - name: Build
      run: make toolchain
        
    - name: Update latest tag
      if: env.isRelease == 'true'
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        allowUpdates: true
        replacesArtifacts: true
        prerelease: true
        artifacts: output/host

    - name: 'Package output'
      run: tar -cvf output.tar output/

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: toolchain
        path: output.tar